In [15]:
#Assignment
# 1.Create a null vector of size 10 but the fifth value which is 1
import numpy as np
vector = np.zeros(10)
vector[4] = 1
print(vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [16]:
# 2.Create a vector with values ranging from 10 to 49.
vector = np.arange(10,50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [19]:
# 3. Create a 3x3 matrix with values ranging from 0 to 8
matrix = np.arange(9).reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [20]:
# 4.Find indices of non-zero elements from [1,2,0,0,4,0]
non_zero = np.nonzero([1,2,0,0,4,0])
print(non_zero)

(array([0, 1, 4]),)


In [35]:
# 5.Create a 10x10 array with random values and find the minimum and maximum values.
arr = np.random.randint(low=1,high=101,size=(10,10))
print(arr)
print("\nMinimum Value :", arr.min())
print("\nMaxium Value :", arr.max())

[[ 59  77  83  42  65  70  76  22  37  83]
 [ 90  22  26  45   2   5   2  14  34  93]
 [ 45  89   4  25  24  68  74  50  10  61]
 [ 87  13  97  31  27  44  53  17   2   5]
 [ 99  79  94  48  36  58  52  82  48  92]
 [  5   6  16  46  14  66  33  96  37  59]
 [ 97  25  69  53  90  14  23  59 100  86]
 [ 50  18  49  51  42  42  27  86  45  47]
 [ 90 100   5  10  53  57  49  46  25  73]
 [ 45  56  48 100  74  40   9  21  87  79]]

Minimum Value : 2

Maxium Value : 100


In [34]:
# 6.Create a random vector of size 30 and find the mean value.
arr = np.random.random(30)
mean = arr.mean()
print("Array of random value\n", arr)
print("\n\nMean value : ",mean)

Array of random value
 [8.35101800e-01 1.26319792e-01 5.06510713e-01 9.80092289e-01
 5.59534397e-01 2.70904083e-01 5.23218540e-01 9.22270175e-01
 7.10527446e-01 3.12397416e-01 5.91127718e-01 9.53189227e-01
 4.26189453e-01 4.45327343e-01 6.13228697e-02 3.48182719e-01
 1.72873039e-01 7.85644384e-01 8.88433053e-01 5.27474117e-01
 3.53539504e-04 7.68458326e-01 8.00822761e-01 7.80935538e-01
 5.07974988e-02 3.39512701e-01 1.14154541e-01 3.00567121e-01
 2.31417025e-01 1.06075246e-01]


Mean value :  0.48132449564323115
